apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk
  template:
    metadata:
      labels:
        app: risk
    spec:
      containers:
        - name: risk
          image: ghcr.io/noeljackson/stocks:dev
          command: ["/risk"]
          envFrom:
            - configMapRef: { name: stocks-config }
            - secretRef: { name: stocks-secrets }
          resources:
            requests: { cpu: 25m, memory: 32Mi }
            limits: { memory: 128Mi }
